services:
  database:
    image: mariadb:10.9
    volumes:
      - ./mariadb-data:/var/lib/mysql
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_ROOT_PASSWORD: 'my-secret-pw'
      MARIADB_DATABASE: 'todo_database'
      MARIADB_USER: 'user'
      MARIADB_PASSWORD: '1234'
    ports:
      - 3001:3306


 # backend:
  #   container_name: backend
  #   restart: always
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SERVER_PORT=8080
  #     - SPRING_DATASOURCE_URL=jdbc:mariadb://localhost:3001/todo_database
  #   depends_on:
  #     - database
  #   build:
  #     context: ./backend-todo-daniel-enrique
  #     dockerfile: Dockerfile


# networks:
#   nesjs-network:

  # dev:
  #   container_name: nestjs_api_dev
  #   image: nestjs-api-dev:1.0.0
  #   build:
  #     context: ./backend-todo-daniel-enrique
  #     target: development
  #     dockerfile: ./Dockerfile
  #   command: npm run start:debug
  #   ports:
  #     - 3000:3000
  #     - 9229:9229
  #   networks:
  #     - nesjs-network
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped
  #   depends_on:
  #     - database
  # prod:
  #   container_name: nestjs_api_prod
  #   image: nestjs-api-prod:1.0.0
  #   build:
  #     context: ./backend-todo-daniel-enrique
  #     target: production
  #     dockerfile: ./Dockerfile
  #   command: npm run start:prod
  #   ports:
  #     - 3000:3000
  #     - 9229:9229
  #   networks:
  #     - nesjs-network
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped
  #   depends_on:
  #     - database


