services:
  db:
    image: mariadb:10.9
    volumes:
       - ./mariadb-data:/var/lib/mysql
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_ROOT_PASSWORD: 'my-secret-pw'
      MARIADB_DATABASE: 'todo_database'
      MARIADB_USER: 'root'
      MARIADB_PASSWORD: 'root'
    ports:
      - 3001:3306
